[[CURRENCIES]]
code = "GOAi"
issuer = "rHTCgtrMj7YMcqM6U28pfnfD2AXuiywRv1"
network = "main"
description = "GOLDAi Token: A fixed-supply digital asset combining the timeless value of gold with the intelligence of AI."
status = "active"
